jwt:
  secret: 'inonu_social_secret'
spring:

  #datasource configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/inonusosyal
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      generate_statistics: true
      ddl-auto: validate

  mail:
    host: smtp.gmail.com
    port: 587
    username: inonusocial@gmail.com
    password: InonuSocial1975#

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

  flyway:
    locations: classpath:db/migration/
    out-of-order: true