spring:

  #datasource configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/inonusosyal
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      generate_statistics: true
      ddl-auto: validate
